name: Python script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update Readme
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: running
      run: |
        python index.py
        git config --global user.name github-actions
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Update README.md
      run: |
        git add README.md
        git commit -am "updating README.md" ||  true
        git push --force origin HEAD:$GITHUB_REF || true

