name: Python script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update Readme
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: running
      run: |
        python index.py
        

